services:
  db:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=test_env
      - MYSQL_DATABASE=wordpress
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  wp-web:
    build: "."
    ports:
    - "8000:8000"
    depends_on:
      - "db"
    links:
      - "db:mysql"
